// <auto-generated />
using System;
using API_Completa.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APICompleta.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20230419130244_agregarNumeroApiTabla")]
    partial class agregarNumeroApiTabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Completa.Modelos.Api", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Apis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "Una nueva y magnifica Api",
                            FechaActualizacion = new DateTime(2023, 4, 19, 9, 2, 44, 552, DateTimeKind.Local).AddTicks(6713),
                            FechaCreacion = new DateTime(2023, 4, 19, 9, 2, 44, 552, DateTimeKind.Local).AddTicks(6678),
                            ImagenUrl = "",
                            MetrosCuadrados = 50,
                            Nombre = "Nueva Api",
                            Ocupantes = 5,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "Una nueva y magnifica Api 2",
                            FechaActualizacion = new DateTime(2023, 4, 19, 9, 2, 44, 552, DateTimeKind.Local).AddTicks(6719),
                            FechaCreacion = new DateTime(2023, 4, 19, 9, 2, 44, 552, DateTimeKind.Local).AddTicks(6717),
                            ImagenUrl = "",
                            MetrosCuadrados = 50,
                            Nombre = "Nueva Api 2",
                            Ocupantes = 5,
                            Tarifa = 200.0
                        });
                });

            modelBuilder.Entity("API_Completa.Modelos.NumeroApi", b =>
                {
                    b.Property<int>("ApiNo")
                        .HasColumnType("int");

                    b.Property<int>("ApiId")
                        .HasColumnType("int");

                    b.Property<string>("DetalleEspecial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.HasKey("ApiNo");

                    b.HasIndex("ApiId");

                    b.ToTable("NumeroApis");
                });

            modelBuilder.Entity("API_Completa.Modelos.NumeroApi", b =>
                {
                    b.HasOne("API_Completa.Modelos.Api", "Api")
                        .WithMany()
                        .HasForeignKey("ApiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Api");
                });
#pragma warning restore 612, 618
        }
    }
}
