// <auto-generated />
using System;
using API_Completa.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APICompleta.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Completa.Modelos.Api", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Apis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "Una nueva y magnifica Api",
                            FechaActualizacion = new DateTime(2023, 4, 18, 9, 18, 41, 973, DateTimeKind.Local).AddTicks(4822),
                            FechaCreacion = new DateTime(2023, 4, 18, 9, 18, 41, 973, DateTimeKind.Local).AddTicks(4783),
                            ImagenUrl = "",
                            MetrosCuadrados = 50,
                            Nombre = "Nueva Api",
                            Ocupantes = 5,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "Una nueva y magnifica Api 2",
                            FechaActualizacion = new DateTime(2023, 4, 18, 9, 18, 41, 973, DateTimeKind.Local).AddTicks(4830),
                            FechaCreacion = new DateTime(2023, 4, 18, 9, 18, 41, 973, DateTimeKind.Local).AddTicks(4828),
                            ImagenUrl = "",
                            MetrosCuadrados = 50,
                            Nombre = "Nueva Api 2",
                            Ocupantes = 5,
                            Tarifa = 200.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
